# Generated by Django 6.1 on 2026-08-11 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RulePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(default='ODOL', max_length=50)),
                ('version', models.IntegerField()),
                ('origin', models.CharField(choices=[('CENTRAL', 'Central'), ('CLIENT', 'Client')], max_length=20)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('domain', 'origin', 'version'), name='unique_rule_pack_version')],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('GROSS_WEIGHT', 'Gross Weight'), ('AXLE_LOAD', 'Axle Load'), ('DIMENSION_LENGTH', 'Length'), ('DIMENSION_WIDTH', 'Width'), ('DIMENSION_HEIGHT', 'Height'), ('AXLE_CONFIG', 'Axle Config')], max_length=50)),
                ('operator', models.CharField(choices=[('LTE', '<='), ('GTE', '>='), ('EQ', '==')], max_length=10)),
                ('threshold', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('axle_config', models.JSONField(blank=True, null=True)),
                ('axle_index', models.IntegerField(blank=True, null=True)),
                ('legal_citation', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('rule_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rules.rulepack')),
            ],
        ),
    ]
