# Generated by Django 6.1 on 2026-08-11 10:34
import uuid
from django.db import migrations

def seed_central_rules(apps, schema_editor):
    RulePack = apps.get_model('rules', 'RulePack')
    Rule = apps.get_model('rules', 'Rule')

    central_pack = RulePack.objects.create(
        id="c0a80101-0000-4000-8000-000000000001",
        domain="ODOL",
        version=3,
        origin="CENTRAL"
    )

    rules_data = [
        # Gross weight
        {
            "dimension": "GROSS_WEIGHT",
            "operator": "LTE",
            "threshold": 25000,
            "unit": "kg",
            "legal_citation": "PM 111/2015 Pasal 4 ayat (2)"
        },
        # Axle loads
        {
            "dimension": "AXLE_LOAD",
            "operator": "LTE",
            "threshold": 10000,
            "unit": "kg",
            "axle_index": 0,
            "legal_citation": "PM 111/2015 Pasal 4 ayat (2)"
        },
        {
            "dimension": "AXLE_LOAD",
            "operator": "LTE",
            "threshold": 16100,
            "unit": "kg",
            "axle_index": 1,
            "legal_citation": "PM 111/2015 Pasal 4 ayat (2)"
        },
        # Dimensions
        {
            "dimension": "DIMENSION_LENGTH",
            "operator": "LTE",
            "threshold": 18000,
            "unit": "mm",
            "legal_citation": "PM 111/2015 Pasal 5"
        },
        {
            "dimension": "DIMENSION_WIDTH",
            "operator": "LTE",
            "threshold": 2500,
            "unit": "mm",
            "legal_citation": "PM 111/2015 Pasal 5"
        },
        {
            "dimension": "DIMENSION_HEIGHT",
            "operator": "LTE",
            "threshold": 4200,
            "unit": "mm",
            "legal_citation": "PM 111/2015 Pasal 5"
        },
    ]

    for data in rules_data:
        Rule.objects.create(rule_pack=central_pack, **data)

def reverse_seed(apps, schema_editor):
    RulePack = apps.get_model('rules', 'RulePack')
    RulePack.objects.filter(id="c0a80101-0000-4000-8000-000000000001").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_central_rules, reverse_seed),
    ]
