# Generated by Django 6.1 on 2026-08-11 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_seed_odol_central_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('page_count', models.IntegerField()),
                ('classification', models.CharField(choices=[('INTERNAL_POLICY', 'Internal Policy'), ('PUBLIC_REGULATION', 'Public Regulation'), ('OPERATIONAL_DOC', 'Operational Doc'), ('UNREADABLE', 'Unreadable'), ('UNRELATED', 'Unrelated')], max_length=50)),
                ('classification_confidence', models.FloatField()),
                ('accepted', models.BooleanField(default=False)),
                ('rejection_reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleCandidate',
            fields=[
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('GROSS_WEIGHT', 'Gross Weight'), ('AXLE_LOAD', 'Axle Load'), ('DIMENSION_LENGTH', 'Length'), ('DIMENSION_WIDTH', 'Width'), ('DIMENSION_HEIGHT', 'Height'), ('AXLE_CONFIG', 'Axle Config')], max_length=50)),
                ('operator', models.CharField(choices=[('LTE', '<='), ('GTE', '>='), ('EQ', '==')], max_length=10)),
                ('threshold', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('applies_to', models.JSONField(blank=True, null=True)),
                ('source_reference', models.CharField(max_length=255)),
                ('source_text_excerpt', models.TextField()),
                ('source_page', models.IntegerField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rule_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='rules.document')),
            ],
        ),
    ]
