# Generated by Django 6.1 on 2026-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_document_rulecandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
