# Generated by Django 6.1 on 2026-08-12
from django.db import migrations

def seed_fallback_axle_rule(apps, schema_editor):
    RulePack = apps.get_model('rules', 'RulePack')
    Rule = apps.get_model('rules', 'Rule')

    try:
        central_pack = RulePack.objects.get(id="c0a80101-0000-4000-8000-000000000001")
    except RulePack.DoesNotExist:
        return

    Rule.objects.create(
        rule_pack=central_pack,
        dimension="AXLE_LOAD",
        operator="LTE",
        threshold=10000,
        unit="kg",
        axle_index=None,  # Fallback for any unmatched axle
        axle_config=None,
        legal_citation="PP 55/2012 (Batas Sumbu Tunggal Universal)"
    )

def reverse_seed(apps, schema_editor):
    Rule = apps.get_model('rules', 'Rule')
    Rule.objects.filter(
        dimension="AXLE_LOAD", 
        axle_index__isnull=True, 
        axle_config__isnull=True
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_seed_detailed_axle_rules'),
    ]

    operations = [
        migrations.RunPython(seed_fallback_axle_rule, reverse_seed),
    ]
