# Generated by Django 6.1 on 2026-08-12
from django.db import migrations

def seed_client_rules(apps, schema_editor):
    RulePack = apps.get_model('rules', 'RulePack')
    Rule = apps.get_model('rules', 'Rule')

    client_pack, created = RulePack.objects.get_or_create(
        id="c0a80101-0000-4000-8000-000000000002",
        defaults={
            "domain": "ODOL",
            "version": 1,
            "origin": "CLIENT"
        }
    )

    rules_data = [
        {
            "dimension": "GROSS_WEIGHT",
            "operator": "LTE",
            "threshold": 22000,
            "unit": "kg",
            "legal_citation": "SOP Internal Gudang Cikarang v2 \u00a73.1"
        },
        {
            "dimension": "DIMENSION_HEIGHT",
            "operator": "LTE",
            "threshold": 4000,
            "unit": "mm",
            "legal_citation": "SOP Internal Gudang Cikarang v2 \u00a73.1"
        }
    ]

    for data in rules_data:
        Rule.objects.create(rule_pack=client_pack, **data)

def reverse_seed(apps, schema_editor):
    RulePack = apps.get_model('rules', 'RulePack')
    RulePack.objects.filter(id="c0a80101-0000-4000-8000-000000000002").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_seed_fallback_axle_rules'),
    ]

    operations = [
        migrations.RunPython(seed_client_rules, reverse_seed),
    ]
