# Generated by hand on 2026-08-13.
#
# 0007 seeded the client SOP rules so the closing beat worked with no manual
# setup. That safety net cost the demo its point: the narrative is "upload the
# SOP, approve it, watch the same dispatch flip to HOLD", and a rule that is
# already active before the upload makes that story theatre.
#
# The live path is real — apps/rules/views.py approve_candidate does
# get_or_create on the CLIENT pack and writes an ACTIVE Rule — so removing the
# seed does not remove the capability, only the head start.
#
# This has to be a migration rather than an edit to 0007: 0007 is already
# applied on the deployed database, and Django never re-runs an applied
# migration. Editing it would change nothing in production.
from django.db import migrations

SEEDED_PACK_ID = "c0a80101-0000-4000-8000-000000000002"
SEEDED_CITATION = "SOP Internal Gudang Cikarang v2 §3.1"


def unseed_client_rules(apps, schema_editor):
    RulePack = apps.get_model("rules", "RulePack")
    Rule = apps.get_model("rules", "Rule")

    pack = RulePack.objects.filter(id=SEEDED_PACK_ID).first()
    if pack is None:
        return

    # Delete by citation rather than dropping the pack outright. views.py
    # resolves the CLIENT pack with get_or_create(domain, origin), so a rule
    # approved through Rule Studio lands in this same pack — a blind delete
    # would take somebody's approved rule with it.
    Rule.objects.filter(rule_pack=pack, legal_citation=SEEDED_CITATION).delete()

    # Only once nothing else lives here. An empty pack is harmless, but leaving
    # it means the next approval reuses this id, which reads as though the
    # seeded pack came back.
    if not Rule.objects.filter(rule_pack=pack).exists():
        pack.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0007_seed_client_rules"),
    ]

    operations = [
        # Deliberately irreversible. Reversing would re-seed the rule this
        # migration exists to remove, and the way to get it back is the one the
        # demo shows: upload the SOP and approve it.
        migrations.RunPython(unseed_client_rules, migrations.RunPython.noop),
    ]
