# Generated by Django 6.1 on 2026-08-13
from django.db import migrations

def update_thresholds(apps, schema_editor):
    Rule = apps.get_model('rules', 'Rule')
    
    # Update tandem
    Rule.objects.filter(
        dimension="AXLE_LOAD",
        axle_index=1,
        threshold=16000
    ).update(
        threshold=18000,
        legal_citation="PP 55/2012 Lampiran (Sumbu Ganda/Tandem)"
    )
    # Ensure any that had the old "Asumsi" string also get updated
    Rule.objects.filter(
        dimension="AXLE_LOAD",
        axle_index=1,
        legal_citation__contains="Asumsi"
    ).update(
        legal_citation="PP 55/2012 Lampiran (Sumbu Ganda/Tandem)"
    )
    
    # Update gross weight
    Rule.objects.filter(
        dimension="GROSS_WEIGHT",
        threshold=25000
    ).update(
        threshold=24000,
        legal_citation="PP 55/2012 Lampiran JBI (Kelas I)"
    )
    Rule.objects.filter(
        dimension="GROSS_WEIGHT",
        legal_citation__contains="Asumsi"
    ).update(
        legal_citation="PP 55/2012 Lampiran JBI (Kelas I)"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_unseed_client_rules'),
    ]

    operations = [
        migrations.RunPython(update_thresholds, migrations.RunPython.noop),
    ]
