# Generated by Django 6.1 on 2026-08-11 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('axle_config', models.CharField(help_text='e.g. 1.2 or 1.22', max_length=20)),
                ('tare_weight_kg', models.IntegerField()),
                ('max_length_mm', models.IntegerField()),
                ('max_width_mm', models.IntegerField()),
                ('max_height_mm', models.IntegerField()),
            ],
        ),
    ]
