# Generated by Django 6.1 on 2026-08-11 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchDecision',
            fields=[
                ('decision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('PASS', 'Pass'), ('HOLD', 'Hold')], max_length=10)),
                ('dispatch_ref', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(help_text='Original request payload')),
                ('rule_packs_applied', models.JSONField(help_text='List of rule packs applied')),
                ('latency_ms', models.IntegerField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('overridden_by', models.CharField(blank=True, max_length=255, null=True)),
                ('override_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=50)),
                ('axle_index', models.IntegerField(blank=True, null=True)),
                ('actual_value', models.IntegerField()),
                ('limit_value', models.IntegerField()),
                ('excess_value', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('severity', models.CharField(choices=[('BLOCKING', 'Blocking'), ('WARNING', 'Warning')], max_length=20)),
                ('rule_origin', models.CharField(max_length=20)),
                ('legal_citation', models.CharField(max_length=255)),
                ('directive', models.TextField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='audit.dispatchdecision')),
            ],
        ),
    ]
