# Generated by Django 6.1 on 2026-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdecision',
            name='override_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
